# Generated by Django 3.2.10 on 2022-01-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220104_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='restock_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
